# Generated by Django 3.2.4 on 2021-06-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Answer')),
                ('answer', models.CharField(max_length=250, verbose_name='Answer')),
                ('user_answer', models.TextField(max_length=250, verbose_name='User Answer')),
            ],
        ),
    ]
