# Generated by Django 3.2.4 on 2021-06-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer1',
            field=models.CharField(default='', max_length=250, verbose_name='answer1'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2',
            field=models.CharField(default='', max_length=250, verbose_name='answer2'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer3',
            field=models.CharField(default='', max_length=250, verbose_name='answer3'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer4',
            field=models.CharField(default='', max_length=250, verbose_name='answer4'),
        ),
        migrations.AddField(
            model_name='questions',
            name='true_answer',
            field=models.CharField(default='', max_length=250, verbose_name='True Answer'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user_answer',
            field=models.TextField(default='-', max_length=250, verbose_name='User Answer'),
        ),
    ]
